global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
  
  - job_name: 'web'
    static_configs:
      - targets: ['web:8000']
  
  - job_name: 'apache'
    static_configs:
      - targets: ['apache:80']