# Generated by Django 5.1.1 on 2024-10-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PongResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=200)),
                ('player2', models.CharField(max_length=200)),
                ('score_player1', models.CharField(max_length=10)),
                ('score_player2', models.CharField(max_length=10)),
                ('gameType', models.CharField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'pong_result',
                'ordering': ['-date'],
            },
        ),
    ]
