# Generated by Django 5.1.2 on 2024-10-17 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong'), ('Card', 'Card')], max_length=255)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'tournament',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PongGameResult',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest1', models.CharField(blank=True, max_length=255, null=True)),
                ('guest2', models.CharField(blank=True, max_length=255, null=True)),
                ('score_player1', models.CharField(max_length=255)),
                ('score_player2', models.CharField(max_length=255)),
                ('game', models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong')], default='RollandGapong', max_length=255)),
                ('mode', models.CharField(choices=[('IA', 'IA'), ('COOP', 'COOP'), ('TOURNAMENT', 'TOURNAMENT'), ('LOCAL1V1', 'LOCAL1V1')], default='LOCAL1v1', max_length=255)),
                ('game_duration', models.TimeField()),
                ('date', models.DateTimeField()),
                ('tournament_phase', models.CharField(blank=True, max_length=255, null=True)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
            options={
                'db_table': 'pong_result',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CardGameResult',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('guest1', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateTimeField()),
                ('game', models.CharField(default='CardGame', max_length=255)),
                ('mode', models.CharField(choices=[('SOLO', 'SOLO'), ('TOURNAMENT', 'TOURNAMENT')], default='SOLO', max_length=255)),
                ('game_duration', models.TimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tournament')),
            ],
            options={
                'db_table': 'card_result',
                'ordering': ['-date'],
            },
        ),
    ]
