# Generated by Django 5.1.2 on 2024-10-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong'), ('Card', 'Card')], max_length=255),
        ),
    ]
