# Generated by Django 5.1.2 on 2024-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgameresult',
            name='guest1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
