# Generated by Django 5.1.2 on 2024-10-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ponggameresult',
            name='game',
            field=models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong')], default='RollandGapong', max_length=20),
        ),
    ]
