# Generated by Django 5.1.2 on 2024-10-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_ponggameresult_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgameresult',
            name='mode',
            field=models.CharField(choices=[('SOLO', 'SOLO'), ('TOURNAMENT', 'TOURNAMENT')], default='SOLO', max_length=20),
        ),
        migrations.AddField(
            model_name='ponggameresult',
            name='mode',
            field=models.CharField(choices=[('IA', 'IA'), ('COOP', 'COOP'), ('TOURNAMENT', 'TOURNAMENT'), ('LOCAL1V1', 'LOCAL1V1')], default='LOCAL1v1', max_length=20),
        ),
    ]
