# Generated by Django 5.1.2 on 2024-10-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cardgameresult_mode_ponggameresult_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardgameresult',
            name='game',
            field=models.CharField(default='CardGame', max_length=255),
        ),
        migrations.AlterField(
            model_name='cardgameresult',
            name='mode',
            field=models.CharField(choices=[('SOLO', 'SOLO'), ('TOURNAMENT', 'TOURNAMENT')], default='SOLO', max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='game',
            field=models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong')], default='RollandGapong', max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='mode',
            field=models.CharField(choices=[('IA', 'IA'), ('COOP', 'COOP'), ('TOURNAMENT', 'TOURNAMENT'), ('LOCAL1V1', 'LOCAL1V1')], default='LOCAL1v1', max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='player2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='score_player1',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='score_player2',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ponggameresult',
            name='tournament_phase',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game_type',
            field=models.CharField(choices=[('RollandGapong', 'RollandGapong'), ('Cyberpong', 'Cyberpong'), ('card', 'Card')], max_length=255),
        ),
    ]
